[2024-09-25 10:03:42,989: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-25 10:03:42,991: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 10:03:42,992: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 10:03:42,993: INFO: common: created directory at: artifacts]
[2024-09-25 10:03:42,994: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-25 10:03:44,235: INFO: data_ingestion: artifacts/data_ingestion/Lstm_Dates.xlsx downloaded! with the following info: 
Server: GitHub.com
Date: Wed, 25 Sep 2024 04:33:40 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
ETag: W/"0051d8858d21d8fc527b10cdbe9cc1f8"
Cache-Control: max-age=0, private, must-revalidate
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'none'; base-uri 'self'; child-src github.com/assets-cdn/worker/ github.com/webpack/ github.com/assets/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com *.rel.tunnels.api.visualstudio.com wss://*.rel.tunnels.api.visualstudio.com objects-origin.githubusercontent.com copilot-proxy.githubusercontent.com api.githubcopilot.com api.individual.githubcopilot.com api.business.githubcopilot.com api.enterprise.githubcopilot.com proxy.individual.githubcopilot.com proxy.business.githubcopilot.com proxy.enterprise.githubcopilot.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ productionresultssa10.blob.core.windows.net/ productionresultssa11.blob.core.windows.net/ productionresultssa12.blob.core.windows.net/ productionresultssa13.blob.core.windows.net/ productionresultssa14.blob.core.windows.net/ productionresultssa15.blob.core.windows.net/ productionresultssa16.blob.core.windows.net/ productionresultssa17.blob.core.windows.net/ productionresultssa18.blob.core.windows.net/ productionresultssa19.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com copilot-workspace.githubnext.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: blob: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com private-avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.com/assets-cdn/worker/ github.com/webpack/ github.com/assets/ gist.github.com/assets-cdn/worker/
Set-Cookie: _gh_sess=C7zpjE32g45p9YXGcxDrQesBC%2BsyXwxMdZZFoTjNMx0OMqQVagegEntfs5zZphIkZLFaU9BfdS2%2BjZHo1sr6o5QIaplPNq8FMPp2GhP7amj07UBWaEm3HDbxfbtzHsoM%2FI4yOaUZSM7lXvecVhE39dDiESROlTC3cvWP2Vuoa8ebnZ4fBln9dzs5ZBAe8jg1ucdboQB0cKxyFfPv5h3nnhUegKQVmqymcASB8XAwL1kShxWjEZwtIadFnpP1ap%2BWzQX2AlIMqRh17g9yAsMbEA%3D%3D--uGlv9QapttfK%2FPvF--WEOGLPLPP3AvN7zwxJe%2FrA%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.481086857.1727238820; Path=/; Domain=github.com; Expires=Thu, 25 Sep 2025 04:33:40 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Thu, 25 Sep 2025 04:33:40 GMT; HttpOnly; Secure; SameSite=Lax
Accept-Ranges: bytes
Transfer-Encoding: chunked
X-GitHub-Request-Id: CC18:15C3DF:5D56B6:66D6FE:66F392A4
connection: close

]
[2024-09-25 10:03:44,239: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2024-09-25 10:03:44,239: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-09-25 10:03:44,241: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 10:03:44,243: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 10:03:44,243: ERROR: stage_02_data_validation: An error occurred during data validation: get_data_validation_config() missing 1 required positional argument: 'schema']
[2024-09-25 10:03:44,244: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<]
[2024-09-25 10:04:27,591: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-25 10:04:27,599: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 10:04:27,602: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 10:04:27,603: INFO: common: created directory at: artifacts]
[2024-09-25 10:04:27,604: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-25 10:04:27,604: INFO: data_ingestion: File already exists of size: ~ 294 KB]
[2024-09-25 10:04:27,604: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2024-09-25 10:04:27,604: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-09-25 10:05:00,401: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 10:05:08,496: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 10:05:33,300: ERROR: stage_02_data_validation: An error occurred during data validation: get_data_validation_config() missing 1 required positional argument: 'schema']
[2024-09-25 10:05:38,778: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<]
[2024-09-25 10:06:54,652: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-25 10:06:54,655: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 10:06:54,657: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 10:06:54,657: INFO: common: created directory at: artifacts]
[2024-09-25 10:06:54,658: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-25 10:06:54,658: INFO: data_ingestion: File already exists of size: ~ 294 KB]
[2024-09-25 10:06:54,659: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2024-09-25 10:06:54,659: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-09-25 10:06:54,661: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 10:06:54,662: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 10:06:54,663: INFO: common: created directory at: artifacts/data_validation]
[2024-09-25 10:06:55,076: ERROR: stage_02_data_validation: An error occurred during data validation: File is not a zip file]
[2024-09-25 10:06:55,077: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<]
[2024-09-25 10:07:45,652: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-25 10:07:45,661: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 10:07:45,665: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 10:07:45,666: INFO: common: created directory at: artifacts]
[2024-09-25 10:07:45,666: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-25 10:07:45,667: INFO: data_ingestion: File already exists of size: ~ 294 KB]
[2024-09-25 10:07:45,667: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2024-09-25 10:07:45,667: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-09-25 10:07:53,097: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 10:07:53,101: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 10:08:38,318: INFO: common: created directory at: artifacts/data_validation]
[2024-09-25 10:09:40,378: ERROR: stage_02_data_validation: An error occurred during data validation: File is not a zip file]
[2024-09-25 10:09:49,658: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<]
[2024-09-25 10:18:24,378: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-25 10:18:24,380: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 10:18:24,381: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 10:18:24,382: INFO: common: created directory at: artifacts]
[2024-09-25 10:18:24,382: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-25 10:18:24,383: INFO: data_ingestion: File already exists of size: ~ 91 KB]
[2024-09-25 10:18:24,383: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<]
[2024-09-25 10:18:24,383: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-09-25 10:18:24,385: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 10:18:24,386: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 10:18:24,387: INFO: common: created directory at: artifacts/data_validation]
[2024-09-25 10:18:24,947: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<]
[2024-09-25 12:29:48,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 12:29:48,075: ERROR: 3874234406: An error occurred during data preprocessing: too many values to unpack (expected 2)]
[2024-09-25 12:30:50,387: ERROR: 2437044159: An error occurred during data preprocessing: [Errno 2] No such file or directory: 'config\\config.yaml']
[2024-09-25 12:31:02,036: ERROR: 2437044159: An error occurred during data preprocessing: [Errno 2] No such file or directory: 'config\\config.yaml']
[2024-09-25 12:31:32,787: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 12:31:32,788: ERROR: 2437044159: An error occurred during data preprocessing: too many values to unpack (expected 2)]
[2024-09-25 12:33:20,296: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 12:33:20,297: ERROR: 2437044159: An error occurred during data preprocessing: too many values to unpack (expected 2)]
[2024-09-25 13:43:05,589: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 13:43:05,591: ERROR: 427244460: An error occurred during data preprocessing: too many values to unpack (expected 2)]
[2024-09-25 13:43:20,608: ERROR: 427244460: An error occurred during data preprocessing: [Errno 2] No such file or directory: 'config\\config.yaml']
[2024-09-25 13:44:17,047: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 13:44:17,048: ERROR: 427244460: An error occurred during data preprocessing: too many values to unpack (expected 2)]
[2024-09-25 13:49:11,306: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 13:50:10,952: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 13:50:10,957: INFO: common: created directory at: artifacts/data_preprocessing]
[2024-09-25 13:50:28,353: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 13:50:28,353: INFO: common: created directory at: artifacts/data_preprocessing]
[2024-09-25 13:50:35,080: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 13:50:35,082: INFO: common: created directory at: artifacts/data_preprocessing]
[2024-09-25 13:50:42,094: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 13:50:42,096: INFO: common: created directory at: artifacts/data_preprocessing]
[2024-09-25 14:23:21,477: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-09-25 14:23:21,478: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 14:23:21,481: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 14:23:21,482: INFO: common: created directory at: artifacts/data_validation]
[2024-09-25 14:23:22,097: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<]
[2024-09-25 14:23:22,097: INFO: main: >>>>>> stage Data Preprocessing stage started <<<<<<]
[2024-09-25 14:23:22,113: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 14:23:22,113: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 14:23:22,113: ERROR: stage_03_data_preprocessing: An error occurred during data preprocessing: 'tuple' object has no attribute 'data_preprocessing']
[2024-09-25 14:23:22,113: INFO: main: >>>>>> stage Data Preprocessing stage completed <<<<<<]
[2024-09-25 14:24:35,425: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-09-25 14:24:35,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 14:24:35,439: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 14:24:35,439: INFO: common: created directory at: artifacts/data_validation]
[2024-09-25 14:24:36,346: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<]
[2024-09-25 14:24:36,346: INFO: main: >>>>>> stage Data Preprocessing stage started <<<<<<]
[2024-09-25 14:24:57,889: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 14:24:57,889: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 14:25:46,524: ERROR: stage_03_data_preprocessing: An error occurred during data preprocessing: 'tuple' object has no attribute 'data_preprocessing']
[2024-09-25 14:25:48,836: INFO: main: >>>>>> stage Data Preprocessing stage completed <<<<<<]
[2024-09-25 14:28:44,129: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-09-25 14:28:44,131: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 14:28:44,132: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 14:28:44,133: INFO: common: created directory at: artifacts/data_validation]
[2024-09-25 14:28:44,630: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<]
[2024-09-25 14:28:44,630: INFO: main: >>>>>> stage Data Preprocessing stage started <<<<<<]
[2024-09-25 14:28:44,632: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-25 14:28:44,633: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-25 14:28:44,634: INFO: common: created directory at: artifacts/data_preprocessing]
[2024-09-25 14:28:44,820: INFO: main: >>>>>> stage Data Preprocessing stage completed <<<<<<]
[2024-09-26 14:16:06,573: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 14:16:06,573: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 14:16:06,573: ERROR: 531617980: An error occurred during data preprocessing: __init__() got an unexpected keyword argument 'source_URL']
[2024-09-26 15:09:10,677: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 15:09:10,677: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 15:09:10,691: ERROR: 4282465902: An error occurred during data preprocessing: __init__() got an unexpected keyword argument 'source_URL']
[2024-09-26 15:10:11,460: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 15:10:11,464: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 15:13:52,170: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 15:13:52,174: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 15:13:52,176: ERROR: 4282465902: An error occurred during data preprocessing: __init__() got an unexpected keyword argument 'source_URL']
[2024-09-26 15:17:29,391: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 15:17:29,396: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 15:20:08,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 15:20:08,298: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 15:20:08,300: INFO: common: created directory at: artifacts/data_transformation]
[2024-09-26 15:20:08,852: ERROR: 2201432772: An error occurred during data preprocessing: 'function' object has no attribute 'to_excel']
[2024-09-26 15:22:56,394: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 15:22:56,397: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 15:22:56,399: INFO: common: created directory at: artifacts/data_transformation]
[2024-09-26 15:24:08,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 15:24:08,091: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 15:24:08,092: INFO: common: created directory at: artifacts/data_transformation]
[2024-09-26 15:24:50,762: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 15:24:50,768: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 15:24:50,771: INFO: common: created directory at: artifacts/data_transformation]
[2024-09-26 16:00:18,393: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 16:00:18,405: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 16:00:18,408: INFO: common: created directory at: artifacts/data_transformation]
[2024-09-26 16:02:37,514: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 16:02:37,526: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 16:02:37,529: INFO: common: created directory at: artifacts/data_transformation]
[2024-09-26 16:04:45,952: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 16:04:45,961: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 16:04:45,963: INFO: common: created directory at: artifacts/data_transformation]
[2024-09-26 16:11:43,223: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 16:11:43,227: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 16:11:43,235: INFO: common: created directory at: artifacts/data_transformation]
[2024-09-26 16:32:40,398: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 16:32:40,402: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 16:32:40,407: INFO: common: created directory at: artifacts/data_transformation]
[2024-09-26 16:33:41,034: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 16:33:41,034: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 16:33:41,034: INFO: common: created directory at: artifacts/data_transformation]
[2024-09-26 16:36:50,799: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 16:36:50,804: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 16:36:50,808: INFO: common: created directory at: artifacts/data_transformation]
[2024-09-26 16:43:50,455: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-26 16:43:50,458: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-09-26 16:43:50,460: INFO: common: created directory at: artifacts/data_transformation]
[2024-09-26 16:43:51,003: ERROR: 3251359935: An error occurred during data preprocessing: 'function' object has no attribute 'head']
[2024-10-02 09:37:00,748: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-02 09:37:00,753: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-02 09:37:00,755: INFO: common: created directory at: artifacts/data_transformation]
[2024-10-02 09:43:06,966: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-02 09:43:06,973: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-02 09:43:06,974: INFO: common: created directory at: artifacts/data_transformation]
[2024-10-02 09:45:38,788: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-02 09:45:38,793: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-02 09:45:38,796: INFO: common: created directory at: artifacts/data_transformation]
[2024-10-02 09:47:07,166: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-02 09:47:07,172: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-02 09:47:07,174: INFO: common: created directory at: artifacts/data_transformation]
[2024-10-02 09:47:07,934: ERROR: 4288489063: An error occurred during data preprocessing: 'function' object has no attribute 'head']
[2024-10-02 09:51:44,251: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-02 09:51:44,256: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-02 09:51:44,256: INFO: common: created directory at: artifacts/data_transformation]
[2024-10-02 09:53:00,900: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-02 09:53:00,909: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-02 09:53:00,911: INFO: common: created directory at: artifacts/data_transformation]
[2024-10-02 09:53:01,431: ERROR: 2276061825: An error occurred during data preprocessing: 'function' object has no attribute 'to_excel']
[2024-10-02 09:54:27,332: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-02 09:54:27,335: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-02 09:54:27,337: INFO: common: created directory at: artifacts/data_transformation]
[2024-10-02 09:57:59,912: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-02 09:57:59,918: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-02 09:57:59,922: INFO: common: created directory at: artifacts/data_transformation]
[2024-10-02 10:12:54,795: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-10-02 10:12:54,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-02 10:12:54,800: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-02 10:12:54,800: INFO: common: created directory at: artifacts/data_validation]
[2024-10-02 10:12:55,339: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<]
[2024-10-02 10:12:55,340: INFO: main: >>>>>> stage Data Preprocessing stage started <<<<<<]
[2024-10-02 10:12:55,342: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-02 10:12:55,343: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-02 10:12:55,344: INFO: common: created directory at: artifacts/data_preprocessing]
[2024-10-02 10:12:55,651: INFO: main: >>>>>> stage Data Preprocessing stage completed <<<<<<]
[2024-10-02 10:12:55,651: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-10-02 10:12:55,654: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-02 10:12:55,655: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-02 10:12:55,657: INFO: common: created directory at: artifacts/data_transformation]
[2024-10-02 10:12:55,748: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<]
[2024-10-03 15:22:19,644: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 15:22:19,658: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 15:22:19,658: ERROR: 3610342134: An error occurred during data preprocessing: __init__() got an unexpected keyword argument 'local_data_path']
[2024-10-03 15:23:34,454: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 15:23:34,467: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 15:23:34,468: ERROR: 2646862442: An error occurred during data preprocessing: __init__() got an unexpected keyword argument 'local_data_path']
[2024-10-03 15:26:03,513: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 15:26:03,517: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 15:26:03,520: ERROR: 2646862442: An error occurred during data preprocessing: __init__() got an unexpected keyword argument 'train_x_data_path']
[2024-10-03 15:28:52,274: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 15:28:52,279: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 15:28:52,280: ERROR: 2646862442: An error occurred during data preprocessing: __init__() got an unexpected keyword argument 'target_column']
[2024-10-03 17:11:41,362: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 17:11:41,365: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 17:11:41,366: ERROR: 361695494: An error occurred during data preprocessing: __init__() got an unexpected keyword argument 'target_column']
[2024-10-03 17:18:51,666: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 17:18:51,672: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 17:19:27,916: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 17:19:27,920: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 17:19:27,923: INFO: common: created directory at: artifacts/model_trainer]
[2024-10-03 17:27:48,081: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 17:27:48,083: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 17:27:48,084: INFO: common: created directory at: artifacts/model_trainer]
[2024-10-03 17:27:48,087: ERROR: 2277352655: An error occurred in model trainer : "'ConfigBox' object has no attribute 'local_data_path'"]
[2024-10-03 17:28:42,660: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 17:28:42,663: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 17:28:42,666: INFO: common: created directory at: artifacts/model_trainer]
[2024-10-03 17:28:42,666: ERROR: 4147402720: An error occurred in model trainer : "'ConfigBox' object has no attribute 'local_data_path'"]
[2024-10-03 17:30:20,771: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 17:30:20,774: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 17:30:20,774: INFO: common: created directory at: artifacts/model_trainer]
[2024-10-03 17:30:21,567: ERROR: 3964945739: An error occurred in model trainer : 'ModelTrainerConfig' object has no attribute 'sequence_length']
[2024-10-03 17:31:44,639: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 17:31:44,650: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 17:31:44,652: ERROR: 3964945739: An error occurred in model trainer : __init__() missing 1 required positional argument: 'sequence_length']
[2024-10-03 17:33:12,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 17:33:12,745: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 17:33:12,746: INFO: common: created directory at: artifacts/model_trainer]
[2024-10-03 17:33:13,146: ERROR: 3964945739: An error occurred in model trainer : dict_keys(['name'])]
[2024-10-03 17:35:13,636: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-03 17:35:13,637: INFO: common: yaml file: schema.yaml loaded successfully]
[2024-10-03 17:35:13,637: INFO: common: created directory at: artifacts/model_trainer]
[2024-10-03 17:35:14,051: ERROR: 3964945739: An error occurred in model trainer : {'name': 'pettah_average'}]
